version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: folia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: folia
      POSTGRES_PASSWORD: folia_secret
      POSTGRES_DB: folia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
